server:
  port: 8087

spring:
  datasource:
    dynamic:
      primary: mydb2
      strict: false
      datasource:
        mydb1:
          url: jdbc:mysql://127.0.0.1:3306/mydb1?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        mydb2:
          url: jdbc:mysql://127.0.0.1:3306/mydb2?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
